name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (fast, offline-friendly)
        run: npm ci --prefer-offline --no-audit

      - name: Lint
        run: npm run lint

      - name: Run unit & integration tests
        # Ensure a clean install then run tests in CI mode. Using --if-present
        # makes this step resilient if the script is absent in forks.
        run: npm ci --prefer-offline --no-audit && npm run test --if-present

      - name: Run workspace smoke tests
        run: npm run test:smoke --if-present
